folder: /Users/mkozhukh/Downloads/test
appname: dsfs

server:
  port: 8040
  domain: http://localhost.com
  secret: some-cookie-secret-here

google:
  key: ---
  secret: ---

users:
  - mkozhukh@ya.ru